name: 'Comment PR'
author: 'Nejc Zdovc'
description: 'Action for commenting in the PR'
inputs:
  message:
    description: 'Message for the PR'
    required: true
  single_comment:
    description: 'Would you only like one comment from the action in the PR?'
    default: 'true'
  identifier:
    description: 'Hidden message that is used to identify comment PR'
    default: 'GITHUB_ACTION_COMMENT_PR'
  github_token:
    description: 'Github token that is used for commenting'
    required: true
outputs:
  commented:
    description: 'Tells you if comment was added to the PR or not, boolean'
branding:
  icon: message-square
  color: orange
runs:
  using: 'node12'
  main: 'dist/index.js'
